# Generated by Django 4.2 on 2023-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=30)),
                ('segundo_nom_cli', models.CharField(max_length=30)),
                ('primer_ap_cli', models.CharField(max_length=30)),
                ('segundo_ap_cli', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=60)),
                ('edad', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField()),
                ('direccion_despa', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('cantidad', models.BigIntegerField()),
                ('precio_pedido', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudMant',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('descripcion_solic', models.CharField(max_length=130)),
            ],
            options={
                'db_table': 'solicitud_mant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pnombre_tecnico', models.CharField(max_length=30)),
                ('snombre_tecnico', models.CharField(max_length=30)),
                ('apellidiop_tecnico', models.CharField(max_length=30)),
                ('apellidom_tecnico', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('fecha_venta', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
